version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
      - "9222:9222"
    depends_on:
      - server
    volumes:
      - ./client:/app/
      - /app/node_modules
  server:
    build:
      context: ./server
    environment:
      - MONGO_URI=mongodb://db:27017/mongo
    ports:
      - "5001:5001"
      - "9229:9229"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: on-failure
  db:
    image: mongo:latest
    expose:
      - 27017
    volumes:
      - db-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - "designerdoggies_net"
  data:
    env_file:
      - .env
    build:
      context: ./data
      dockerfile: Dockerfile
      args:
        - DATABASE_URI=$DATABASE_URI
        - USERNAME=$MONGO_INITDB_ROOT_USERNAME
        - PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - db
    networks:
      - "designerdoggies_net"
volumes:
  db-volume:
